### ISSUE TITLE
Documentation: For Installation in Wordpress and various frameworks

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-web-components#33]

**Comment by cairocoder01** [comment]
Related to #21

**Comment by cairocoder01** [comment]
- [x] Basic HTML  (https://github.com/DiscipleTools/disciple-tools-web-components/commit/aec6d7b4fab85080de5b4b42f9b5daa04f54da36)
- [ ] React
- [ ] Vue
