### ISSUE TITLE
Add required and disabled to form-base

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-web-components#6]
Add required and disabled to properties in the form-base and remove them from the individual components.

**Comment by cairocoder01** [comment]
Found this article for hooking into form validation: https://css-tricks.com/creating-custom-form-controls-with-elementinternals/

**Comment by cairocoder01** [comment]
https://github.com/DiscipleTools/disciple-tools-web-components/commit/47f78c62035bc547cc87b76ff1eb9b1a8c7aa33a
